### ISSUE TITLE
Hash should take into account Xcode version

### ISSUE THREAD

**Issue by msanders** [guidomb/carthage_cache#13]
Since Swift frameworks [aren't binary compatible between releases](https://developer.apple.com/swift/blog/?id=2), cached frameworks currently break when developers are on different versions of Xcode or if everyone doesn't upgrade at once. As a workaround, `carthage_cache` could just take into account `xcodebuild -version` when generating the file name for each cache.

(This happened to us today with the release of Xcode 7.3.)

**Comment by guidomb** [comment]
Yes you are right. For now the work around is to do `carthage_cache publish -f` to re upload an archive for a given hash. I'll try to add a patch for this but if you want to give it a shot and send PR I'll really appreciate it.

**Comment by hyperspacemark** [comment]
Since the actual issue here is Swift ABI compatibility, might I suggest hashing with the result of `swift -version` instead of the Xcode version? Multiple Xcode patch versions that share a toolchain shouldn't result in differently hashed archives.

I've been using this to check toolchain versions in our project's Rakefile. (Pardon the Ruby, I only play a rubyist on the internet)

```ruby
def swift_version
  output = `swift -version`.chomp
  version_string = /(\d+\.)?(\d+\.)?(\d+)/.match(output).to_s
  Gem::Version.new(version_string)
end
```

**Comment by msanders** [comment]
@guidomb submitted a PR, let me know what you think

**Comment by guidomb** [comment]
@msanders Thanks for contributing! I'll take a look at it.
